Fix the authorization issue.

diff --git a/bin/dotfile b/bin/dotfile
--- a/bin/dotfile
+++ b/bin/dotfile
@@ -816,8 +816,6 @@ function install_node_versions() {
 #   None
 #######################################
 function install() {
-  print 0 "Beginning installation..."
-
   install_homebrew
 
   configure_homebrew_tap
@@ -1044,14 +1042,20 @@ elif [ ! -d $SourcePath ] || [[ $(is-folder-empty $SourcePath) == $true ]] || [[
   exit 1
 fi
 
+# main program
+# exit the script if any statement returns a non-true return value
+set -e
+
+print 1 "\nLet's go!" && sync
+
+# Ask user provider root password.
+read -p "Please provide password: " -s user_password && echo -e "\n"
+
 # TODO: Make a separate program.
 if [[ "$SourcePath" != "$dotfile_path" ]]; then
   dotfile_path=$SourcePath
   typeset -p dotfile_path > $HOME/.bin/custom-variables
 fi
-
-# Ask user provider root password.
-read -p "Please provide password: " -s user_password && echo -e "\n"
 
 if [[ $Install_Dotfiles == 1 ]]; then
   install
@@ -1068,6 +1072,3 @@ fi
 
 exit $?
 
-# main program
-# exit the script if any statement returns a non-true return value
-# set -e
