Use custom copy file command to replace built-in cp command.
1.Replace all the cp command to copyFile.
2.Fix some typos.
3.Refactor code and comments.

diff --git a/Bin/dotfile b/Bin/dotfile
--- a/Bin/dotfile
+++ b/Bin/dotfile
@@ -3,8 +3,10 @@
 # This program is used to backup or restore dot files.
 #
 # TODO: 1.Try to seperate all backup methods.
-#       2.Add file compare feature.
-#       3.Flexible parameters like dotfile / -i -b ,etc.
+#       2.Flexible parameters like dotfile / -i -b ,etc.
+#       3.Check Application folder for some specific apps like iTerm2.
+#       4.Check the input parameters and related command like basename.
+#       5.Add background color support.
 
 ###################################
 # Declare some constant variables.
@@ -18,7 +20,7 @@ declare -r false=0
 declare -r d_Black='\033[0;30m'
 declare -r d_Red='\033[0;31m'
 declare -r d_Green='\033[0;32m'
-declare -r d_Yellow='\033[1;33m'
+declare -r d_Yellow='\033[0;33m'
 declare -r d_Blue='\033[0;34m'
 declare -r d_White='\033[1;37m'
 declare -r d_NC='\033[0m'
@@ -56,14 +58,14 @@ function print() {
 	      elif [ $1 -eq 1 ]; then
             echo -e "${d_Green}$2${d_NC}" >&1
         elif [ $1 -eq 2 ]; then
-            echo -e "${d_Yello}$2${d_NC}" >&2
+            echo -e "${d_Yellow}$2${d_NC}" >&1 >&2
     	  elif [ $1 -eq 3 ]; then
             echo -e "${d_Red}$2${d_NC}" >&1
     	  else
-       	    echo -e "${d_Red}Status code should only among 0, 1, 2 and 3.${d_NC}" >&2
+       	    echo -e "${d_Red}Status code should only among 0, 1, 2 and 3.${d_NC}" >&1 >&2
         fi
     else
-        echo -e "${d_Red}Please check parameters.${d_NC}" >&2
+        echo -e "${d_Red}Please check parameters.${d_NC}" >&1 >&2
         exit 1
     fi
 }
@@ -71,6 +73,8 @@ function print() {
 #######################################
 # Check command existed or not.
 # Globals:
+#   command
+#   print
 # Arguments:
 #   Command Name
 # Returns:
@@ -92,6 +96,8 @@ function isCommandExist() {
 ################################################
 # Check whether specific server is alive or not.
 # Globals:
+#   ping
+#   print
 # Arguments:
 #   Tool Name
 #   Command Line Name (Optional)
@@ -113,9 +119,83 @@ function isServerAlive () {
     fi
 }
 
+################################################################
+# File copy (If the original file is newer than the target file)
+# Globals:
+#   basename
+#   print
+#   cp
+# Arguments:
+#   Source File Path
+#   Target Folder Path
+# Returns:
+#   None
+################################################################
+function copyFile () {
+    if [ $# -eq 2 ]; then
+        local filename=$(basename $1)
+
+        if [[ ! -f $1 ]]; then
+            print 3 "The file: $1 is not existed."
+            # TODO: Return status code
+        fi
+
+        if [[ ! -d $2 ]]; then
+            print 3 "The source folder: $2 is illegal."
+        fi
+
+        if [[ -f $2/$filename ]]; then
+            if [[ $1 -nt $2/$filename ]]; then
+                cp $1 $2
+                print 1 "File name $filename is replaced."
+            else
+                print 2 "File name $filename don't need to replace."
+            fi
+        else
+            cp $1 $2
+        fi
+    else
+        print 3 "Please check parameters."
+        exit 1
+    fi
+}
+
+################################################################
+# Folder copy (If the original file is newer than the target file)
+# Globals:
+#   copyFile
+#   print
+# Arguments:
+#   Source Folder Path
+#   Target Folder Path
+# Returns:
+#   None
+################################################################
+function copyFolder () {
+    if [ $# -eq 2 ]; then
+        if [[ ! -d $1 ]]; then
+            print 3 "The source folder: $1 is illegal."
+            # TODO: Return status code
+        fi
+
+        if [[ ! -d $2 ]]; then
+            print 3 "The target folder: $2 is illegal."
+        fi
+
+        for filePath in $1/*; do
+            copyFile $filePath $2
+        done
+    else
+        print 3 "Please check parameters."
+        exit 1
+    fi
+}
+
 ################################################
 # Check whether specific folder is empty or not.
 # Globals:
+#   find
+#   print
 # Arguments:
 #   Folder Path
 # Returns:
@@ -138,6 +218,9 @@ function isFolderEmpty () {
 #######################################
 # Using npm tool to install packages.
 # Globals:
+#   isCommandExist
+#   npm
+#   print
 # Arguments:
 #   Tool Name/Command Line Name
 #   Command Line Name (Optional)
@@ -168,6 +251,9 @@ function npmInstallIfNotExist() {
 #######################################
 # Using homebrew to install tool.
 # Globals:
+#   brew
+#   isCommandExist
+#   print
 # Arguments:
 #   Tool Name
 #   Command Line Name (Optional)
@@ -198,6 +284,8 @@ function brewInstallIfNotExist() {
 #############################################
 # Using Git to get latest version or clone.
 # Globals:
+#   git
+#   print
 # Arguments:
 #   Local Folder Path
 #   Remote Repository Name
@@ -222,6 +310,7 @@ function gitCloneOrUpdate() {
                 cd $1
 
                 if [ $# -ge 4 ]; then
+                    print 1 "Checkout to branch: $4."
                     git checkout $4
                 fi
 
@@ -251,6 +340,8 @@ function gitCloneOrUpdate() {
 #######################################
 # Install ruby packages.
 # Globals:
+#   gem
+#   print
 # Arguments:
 #   Package name
 # Returns:
@@ -283,8 +374,11 @@ function rubyPackageInstall() {
 #######################################
 # Install python packages.
 # Globals:
+#   pip2,3
+#   print
 # Arguments:
 #   Package name
+#   Version (3=pip3, 2=pip2)
 # Returns:
 #   None
 #######################################
@@ -314,6 +408,7 @@ function pythonPackageInstall() {
 #######################################
 # Setup Mac OS Inside parameters.
 # Globals:
+#   print
 # Arguments:
 #   None
 # Returns:
@@ -340,6 +435,7 @@ function setupMacOS() {
 #######################################
 # Install custom commands.
 # Globals:
+#   copyFolder
 # Arguments:
 #   None
 # Returns:
@@ -348,25 +444,22 @@ function setupMacOS() {
 function installCustomTools() {
     if [ ! -d "$HOME/.bin" ]; then
         mkdir $HOME/.bin
-    else
-        rm -rf $HOME/.bin/*
     fi
 
-    cp -r $SourcePath/Bin/* $HOME/.bin
+    copyFolder $SourcePath/Bin $HOME/.bin
 }
 
 #######################################
 # Backup custom commands.
 # Globals:
+#   copyFolder
 # Arguments:
 #   None
 # Returns:
 #   None
 #######################################
 function backupCustomTools() {
-    if [ -d $HOME/.bin ]; then
-        cp -r $HOME/.bin/* $SourcePath/Bin/
-    fi
+    copyFolder $HOME/.bin $SourcePath/Bin
 }
 
 #######################################
@@ -402,26 +495,26 @@ function install() {
 
     print 0 "Check git..."
     brewInstallIfNotExist 'git'
-    cp $SourcePath/Git/.gitconfig $HOME/
-    cp $SourcePath/Git/.gitignore_global $HOME/
+    copyFile $SourcePath/Git/.gitconfig $HOME/
+    copyFile $SourcePath/Git/.gitignore_global $HOME/
 
     print 0 "Check python3..."
     brewInstallIfNotExist 'python3'
 
     print 0 "Check mongo database..."
     brewInstallIfNotExist 'mongodb' 'mongo'
-    cp $SourcePath/MongoDB/.mongorc.js $HOME
+    copyFile $SourcePath/MongoDB/.mongorc.js $HOME
 
     print 0 "Check mysql database..."
     brewInstallIfNotExist 'mariadb' 'mysql'
-    cp $SourcePath/MySQL/.my.cnf $HOME
+    copyFile $SourcePath/MySQL/.my.cnf $HOME
 
     print 0 "Check tree tool..."
     brewInstallIfNotExist 'tree'
 
     print 0 "Check Oh-My-Zsh..."
     gitCloneOrUpdate $HOME/.oh-my-zsh ${ohmyzsh[*]}
-    cp $SourcePath/Zsh/.zshrc $HOME
+    copyFile $SourcePath/Zsh/.zshrc $HOME
 
     print 0 "Check tmux tool..."
     brewInstallIfNotExist 'tmux'
@@ -429,13 +522,13 @@ function install() {
     rubyPackageInstall 'tmuxinator'
     gitCloneOrUpdate $HOME/.tmux ${ohmytmux[*]}
     ln -s -f $HOME/.tmux/.tmux.conf $HOME
-    cp $SourcePath/Other/.tmux.conf.local $HOME
+    copyFile $SourcePath/Other/.tmux.conf.local $HOME
 
     # config emacs (substitute the default emacs installed by Mac OS)
     print 0 "Check emacs..."
     brewInstallIfNotExist 'emacs'
     gitCloneOrUpdate $HOME/.emacs.d ${spacemacs[*]}
-    cp $SourcePath/Emacs/.spacemacs $HOME
+    copyFile $SourcePath/Emacs/.spacemacs $HOME
     # Remove this file to avoid the strange characters in the Spacemacs' terminal mode.
     if [ -f "$HOME/.iterm2_shell_integration.zsh" ]; then
         rm $HOME/.iterm2_shell_integration.zsh
@@ -461,11 +554,11 @@ function install() {
     if [ ! -d $HOME/.SpaceVim ]; then
         curl -sLf https://spacevim.org/install.sh | bash
     fi
-    cp $SourcePath/Vim/* $HOME/.SpaceVim.d/
+    copyFile $SourcePath/Vim/* $HOME/.SpaceVim.d/
 
     print 0 "Check ClangFormat tool..."
     brewInstallIfNotExist 'clang-format'
-    cp $SourcePath/Other/.clang-format $HOME
+    copyFile $SourcePath/Other/.clang-format $HOME
 
     print 0 "Check htop tool..."
     brewInstallIfNotExist 'htop'
@@ -479,7 +572,7 @@ function install() {
     source $HOME/.nvm/nvm.sh
 
     print 0 "Check hexo..."
-    # TODO: Need to use 'npm list -g' to determine if packages are existed or not. 
+    # TODO: Need to use 'npm list -g' to determine if packages are existed or not.
     npmInstallIfNotExist 'hexo-cli' 'hexo'
 
     print 0 "Check API BluePrint..."
@@ -490,7 +583,7 @@ function install() {
     rubyPackageInstall 'travis'
 
     print 0 "Check WakaTime tool..."
-    cp $SourcePath/Other/.wakatime.cfg $HOME
+    copyFile $SourcePath/Other/.wakatime.cfg $HOME
 
     print 0 "Create custom tools..."
     installCustomTools
@@ -514,40 +607,40 @@ function install() {
 #######################################
 function backup() {
     print 0 "Backup Oh-My-Zsh..."
-    cp -r $HOME/.zshrc $SourcePath/Zsh/
+    copyFile $HOME/.zshrc $SourcePath/Zsh/
 
     print 0 "Backup emacs..."
-    cp -r $HOME/.spacemacs $SourcePath/Emacs/
+    copyFile $HOME/.spacemacs $SourcePath/Emacs/
 
     print 0 "Backup mongo database..."
-    cp $HOME/.mongorc.js $SourcePath/MongoDB/
+    copyFile $HOME/.mongorc.js $SourcePath/MongoDB/
     # TODO: backup mongo.conf file.
 
     print 0 "Backup mysql database..."
-    cp -r $HOME/.my.cnf $SourcePath/MySQL/
+    copyFile $HOME/.my.cnf $SourcePath/MySQL/
 
     print 0 "Backup clang format information..."
-    cp -r $HOME/.clang-format $SourcePath/Other/
+    copyFile $HOME/.clang-format $SourcePath/Other/
 
     print 0 "Backup tmux tool's configuration..."
-    cp -r $HOME/.tmux.conf.local $SourcePath/Other/
+    copyFile $HOME/.tmux.conf.local $SourcePath/Other/
 
     print 0 "Backup Vim..."
-    cp -r $HOME/.SpaceVim.d/* $SourcePath/Vim
+    copyFolder $HOME/.SpaceVim.d $SourcePath/Vim
 
     print 0 "Backup System Config..."
-    cp -r $HOME/.config/fontconfig/ $SourcePath/Config/fontconfig/
-    cp -r $HOME/.config/tmuxinator/ $SourcePath/Config/tmuxinator/
+    copyFolder $HOME/.config/fontconfig $SourcePath/Config/fontconfig
+    copyFolder $HOME/.config/tmuxinator $SourcePath/Config/tmuxinator
 
     print 0 "Backup Git Configuration..."
-    cp $HOME/.gitconfig $SourcePath/Git/
-    cp $HOME/.gitignore_global $SourcePath/Git/
+    copyFile $HOME/.gitconfig $SourcePath/Git/
+    copyFile $HOME/.gitignore_global $SourcePath/Git/
 
     print 0 "Backup custom tools..."
     backupCustomTools
 
     print 0 "Backup WakaTime Config..."
-    cp $HOME/.wakatime.cfg $SourcePath/Other/
+    copyFile $HOME/.wakatime.cfg $SourcePath/Other/
 
     print 1 "Done."
 }
